### ISSUE TITLE
Restore ability to add more than one phone

### ISSUE THREAD

**Issue by byymster** [byymster/telium#2]
## Description
Restore ability to add more than one phone

![Image](https://github.com/user-attachments/assets/a03e39b3-ed14-430d-abe4-5cf3c9ab6f9e)

**Comment by MAlexAT** [comment]
def add_contact(args, book: AddressBook):
    name, phone, *additional_phones = args
    record = book.find(name)
    message = "Контакт оновлено."
    if record is None:
        record = Record(name)
        book.add_record(record)
        message = "Контакт додано."
    
    if phone:
        record.add_phone(phone)
        
    for additional_phone in additional_phones:
        record.add_phone(additional_phone)

    return message



##Explanation:
name, phone, *additional_phones = args now unpacks the first two arguments into name and phone, and any remaining arguments into the list additional_phones.
The code first checks if a contact with the given name already exists. If not, it creates a new Record for the contact.
The phone variable is added to the contact, and then the loop iterates over additional_phones to add any other phone numbers provided in args.
