### ISSUE TITLE
Extend "birthdays" command

### ISSUE THREAD

**Issue by byymster** [byymster/telium#3]
## Description
In order to  display a list of contacts whose birthday is a specified number of days from the current date please extend `birthdays` command to be able to pass optional argument - days (default, 7)
This argument should be passed down to `AddressBook.get_upcoming_birthdays` method

Example command `birthdays 14` or `birthdays`

**Comment by NotJod563** [comment]
Commit: https://github.com/byymster/telium/pull/5/commits/136c051e523e4afba42f7eae2773e6c31dd5fc74
Pull request: https://github.com/byymster/telium/pull/5
